language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

install:
  - composer self-update
  - composer install --dev --prefer-dist

script:
  - bin/phpunit --verbose --coverage-clover=coverage.clover
  - php bin/phpcs --standard=PSR1 --ignore=vendor .
  - php bin/phpcs --standard=PSR2 --ignore=vendor .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
